Repository nlpsandbox/phi-deidentifier, pull requests merged in 2021-02, with the labels that each got.

#63 [Implements #43] Add Tool Dependencies
  docker-compose.yml
  server/openapi_server/config.py
  server/openapi_server/controllers/deidentified_notes_controller.py
  server/openapi_server/controllers/tool_controller.py
  server/openapi_server/test/test_deidentified_notes_controller.py
  server/openapi_server/test/test_tool_controller.py
  server/openapi_server/test/utils.py
  server/openapi_server/utils/annotator_client.py
  server/openapi_server/utils/annotators.py
Labels: Priority: High

#67 Fix Bug that Broke Requests to Annotators
  server/openapi_server/controllers/deidentified_notes_controller.py
  server/openapi_server/utils/annotators.py
Labels: bug

#71 Enable nginx to be reached but disable internet access to annotators
  docker-compose.yml
  package-lock.json
  package.json
  server/Dockerfile
Labels: Priority: Medium

#76 Update CI/CD workflow based on org template
  .github/workflows/ci.yml
  server/openapi_server/util.py
  server/setup.cfg
  server/tox.ini
Labels: Priority: High

#79 Release 1.0.0
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issue_report.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docker-compose.yml
  server/openapi_server/controllers/security_controller_.py
  server/openapi_server/models/masking_char_config.py
  server/openapi_server/openapi/openapi.yaml
Labels: Priority: High
